<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\MaoTouGu.Shells.WPF\MaoTouGu.Shells.WPF.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="test.i18n">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MaoTouGu.Shells.Generators" Version="1.0.4" />
    </ItemGroup>

</Project>
