<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>disable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>MaoTouGu.Shells.Controls</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\..\..\scaffolds\Usings\ApiRef_WPF.cs">
            <Link>Properties\ApiRef_WPF.cs</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MaoTouGu.Shells\MaoTouGu.Shells.csproj"/>
        <ProjectReference Include="..\..\..\UI\KinonekoSoftware.UI.ColorPicker.OnWPF\KinonekoSoftware.UI.ColorPicker.OnWPF.csproj"/>
        <ProjectReference Include="..\..\..\UI\KinonekoSoftware.UI.OnWPF\KinonekoSoftware.UI.OnWPF.csproj"/>
        <ProjectReference Include="..\..\..\UI\KinonekoSoftware.UI\KinonekoSoftware.UI.csproj"/>
    </ItemGroup>

</Project>
