<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Loggers\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="NLog" Version="5.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Foundation\src\MaoTouGu.Foundation\MaoTouGu.Foundation.csproj" />
      <ProjectReference Include="..\MaoTouGu.Shells.Flyout\MaoTouGu.Shells.Flyout.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Languages\Enum_zh-CN.txt" />
      <EmbeddedResource Include="Languages\Enum_zh-CN.txt" />
    </ItemGroup>
</Project>
