<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyName>MaoTouGu.JuXiaoYou</AssemblyName>
        <RootNamespace>MaoTouGu.JuXiaoYou</RootNamespace>
        <ApplicationIcon>..\..\..\..\assets\icon\JuXiaoYou4.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\windows\MaoTouGu.JuXiaoYou.Core\MaoTouGu.JuXiaoYou.Core.csproj" />
        <ProjectReference Include="..\..\windows\MaoTouGu.JuXiaoYou.Domain.Visualizers\MaoTouGu.JuXiaoYou.Domain.Visualizers.csproj" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="MaoTouGu.Shells.Generators" Version="1.0.4" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="..\..\..\..\assets\icon\JuXiaoYou4.ico">
            <Link>JuXiaoYou4.ico</Link>
        </Resource>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\..\..\scaffolds\Usings\ApiRef_Shells.cs">
          <Link>Properties\ApiRef_Shells.cs</Link>
        </Compile>
        <Compile Include="..\..\..\..\scaffolds\Usings\Usings_Foundation.cs">
            <Link>Properties\Usings_Foundation.cs</Link>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pages\_Debugger\" />
      <Folder Include="Pages\_Launcher\" />
    </ItemGroup>

</Project>
