<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>disable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Pages\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MaoTouGu.Shells.Generators" Version="1.0.4"/>
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\MaoTouGu.JuXiaoYou.Core\MaoTouGu.JuXiaoYou.Core.csproj" />
    </ItemGroup>


    <ItemGroup>
      <Compile Include="..\..\..\..\scaffolds\Usings\ApiRef_Foundation.cs">
        <Link>Properties\ApiRef_Foundation.cs</Link>
      </Compile>
      <Compile Include="..\..\..\..\scaffolds\Usings\ApiRef_LiteDB.cs">
        <Link>Properties\ApiRef_LiteDB.cs</Link>
      </Compile>
      <Compile Include="..\..\..\..\scaffolds\Usings\ApiRef_WPF.cs">
        <Link>Properties\ApiRef_WPF.cs</Link>
      </Compile>
      <Compile Include="..\..\..\..\scaffolds\Usings\Usings_Foundation.cs">
        <Link>Properties\Usings_Foundation.cs</Link>
      </Compile>
      <Compile Include="..\..\..\..\scaffolds\Usings\Usings_MaoTouGu.Shells.cs">
        <Link>Properties\Usings_MaoTouGu.Shells.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
