<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Attributes\" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\CompositableFormDrawer.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
      <Page Update="Views\Controls.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Foundation\src\MaoTouGu.Foundation\MaoTouGu.Foundation.csproj" />
      <ProjectReference Include="..\..\..\Shells\src\MaoTouGu.Shells.WPF\MaoTouGu.Shells.WPF.csproj" />
      <ProjectReference Include="..\..\share\MaoTouGu.JuXiaoYou.Attributes\MaoTouGu.JuXiaoYou.Attributes.csproj" />
    </ItemGroup>

</Project>
